version: '3'
services:
  media-cache:
    image: docker.io/valkey/valkey:7.2.5-bookworm
    ports:
      - 6379:6379
    volumes:
      - ./data:/data
    environment:
      - VALKEY_PASSWORD=${REDIS_PASSWORD}
